version: '3'
services:
  ssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=rstudio-server
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/nginx.key
      - SSL_CSR=/certs/nginx.csr
      - SSL_CERT=/certs/nginx.crt
    networks:
      - proxy-tier

  proxy:
    image: nginx
    container_name: rstudio_docker_proxy
    restart: unless-stopped
    ports:
      - 10443:443/tcp
    volumes:
      - certs:/etc/ssl
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy-tier
    depends_on:
      - ssl

  rstudio:
    build:
      context: ./rstudio
      args:
        - RSTUDIO_VERSION=1.2.5042
        - S6_VERSION=2.0.0.1
    image: rstudio_docker_app
    container_name: rstudio_docker_app
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home:/home
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    networks:
      - proxy-tier

volumes:
  certs:

networks:
  proxy-tier:
