version: '3'
services:

  proxy:
    build:
      context: ./traefik
    image: ${REGISTRY}/rstudio_docker_proxy
    container_name: rstudio_docker_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=(PathPrefix(`/traefik/`) || Headers(`Referer`, `https://${HOST}/traefik/dashboard/`))
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=strip-traefik
      - traefik.http.middlewares.strip-traefik.stripprefix.prefixes=/traefik
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    restart: unless-stopped
    command:
      - "--api"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rstudio-net

  rstudio:
    build:
      context: ./rstudio
      args:
        - R_VERSION=${R_VERSION}
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
        - MINICONDA_VERSION=${MINICONDA_VERSION}
    image: ${REGISTRY}/rstudio_docker_app
    container_name: rstudio_docker_app
    labels:
      - traefik.enable=true
      - traefik.http.routers.rstudio.tls=true
      - traefik.http.routers.rstudio.rule=Host(`rstudio.${HOST}`)
      - traefik.http.services.rstudio.loadbalancer.server.port=8787
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home:/home
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    networks:
      - rstudio-net

networks:
  rstudio-net:
