version: '3'
services:

  proxy:
    build:
      context: ./traefik
    image: rstudio_docker_proxy
    container_name: rstudio_docker_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`${HOST}`)
      # Forward traffic to web ui on port 8080
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    restart: unless-stopped
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rstudio-net

  rstudio:
    build:
      context: ./rstudio
      args:
        - R_VERSION=${R_VERSION}
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
        - MINICONDA_VERSION=${MINICONDA_VERSION}
    image: rstudio_docker_app
    container_name: rstudio_docker_app
    labels:
      - traefik.enable=true
      - traefik.http.routers.rstudio.tls=true
      - traefik.http.routers.rstudio.rule=Host(`rstudio.${HOST}`)
      - traefik.http.services.rstudio.loadbalancer.server.port=8787
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home:/home
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    networks:
      - rstudio-net

networks:
  rstudio-net:
