version: '3'
services:
  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=rstudio-server
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/nginx.key
      - SSL_CSR=/certs/nginx.csr
      - SSL_CERT=/certs/nginx.crt
    networks:
      - proxy-tier

  proxy:
    build: ./proxy
    image: proxy_rstudio
    container_name: proxy_rstudio
    ports:
      - 10443:443/tcp
    volumes:
      - certs:/etc/ssl
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  rstudio:
    build: ./rstudio
    image: rstudio_with_proxy
    container_name: rstudio_with_proxy
    stdin_open: true
    tty: true
    volumes:
       - /home:/home
       - /etc/passwd:/etc/passwd
       - /etc/group:/etc/group
       - /etc/shadow:/etc/shadow
    command: /etc/init.d/rstudio-server start && /bin/bash
    networks:
      - proxy-tier

volumes:
  certs:

networks:
  proxy-tier:
